#!/bin/bash

MAIN_GITHUB_FOLDER_PATH=$1
if [ "$MAIN_GITHUB_FOLDER_PATH" == "" ]; then
    MAIN_GITHUB_FOLDER_PATH=~/github
fi

cd $MAIN_GITHUB_FOLDER_PATH

for d in */ ; do
    cd $MAIN_GITHUB_FOLDER_PATH/$d
    res=$(git status)

    if [[ $res != *"nothing to commit"* ]] || [[ $res != *"branch is up to date with"* ]]; then
        echo -e "\n\n----------------------------------------------------------------\n"
        echo -e "Proj: "$d
        echo -e "Path: "$(pwd)"\n"

        git status

        echo -e "\n----------------------------------------------------------------\n\n"
    fi
done

