#!/bin/bash

MAIN_GITHUB_FOLDER_PATH=$1
if [ "$MAIN_GITHUB_FOLDER_PATH" == "" ]; then
    MAIN_GITHUB_FOLDER_PATH=~/github
fi

cd $MAIN_GITHUB_FOLDER_PATH
summary_to_push=""
summary_to_pull=""
summary_both=""

for d in */ ; do
    path=$MAIN_GITHUB_FOLDER_PATH/$d
    cd $path
    res=$(git status)

    if [[ $res != *"nothing to commit"* ]] || [[ $res != *"branch is up to date with"* ]]; then
        echo -e "\n\n----------------------------------------------------------------\n"
        echo -e "Proj: "$d
        echo -e "Path: $path\n"

        git status

        echo -e "\n----------------------------------------------------------------\n\n"

        if [[ $res != *"nothing to commit"* ]]; then
            summary_to_push="$summary_to_push\n$d"
        fi

        if [[ $res != *"branch is up to date with"* ]]; then
            summary_to_pull="$summary_to_pull\n$d"
        fi

        if [[ $res != *"nothing to commit"* ]] && [[ $res != *"branch is up to date with"* ]]; then
            summary_both="$summary_both\n$d"
        fi
    fi
done

echo -e "\nSummary:\n\nTo pull:$summary_to_pull\n\nTo push:$summary_to_push\n\nBoth:$summary_both"